FROM ubuntu:focal

RUN apt update \
    && DEBIAN_FRONTEND=noninteractive apt install -y gcc g++ cmake binutils git vim astyle ninja-build python3 valgrind \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /root

CMD ["bash"]