FROM ubuntu:cosmic

RUN apt update \
    && apt install -y gcc g++ cmake automake libtool binutils git vim zsh curl astyle \
    && rm -rf /var/lib/apt/lists/*

RUN rm /bin/sh && ln -s /bin/zsh /bin/sh

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

WORKDIR /root

CMD ["zsh"]