FROM ubuntu:cosmic

RUN apt update \
    && apt install -y gcc g++ cmake automake libtool binutils git vim zsh curl locales astyle \
    && rm -rf /var/lib/apt/lists/*

RUN locale-gen "en_US.UTF-8"

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

WORKDIR /root

CMD ["zsh"]