FROM ubuntu:22.04

ENV TZ="America/Los_Angeles"

RUN apt update \
    && DEBIAN_FRONTEND=noninteractive apt install -y gcc g++ cmake binutils git ninja-build python3-sphinx \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /root