if(DEV_BUILD)
    set(CPACK_PACKAGE_NAME ${CMAKE_PROJECT_NAME}-dev)
    set(CPACK_COMPONENTS_ALL Exec Lib StaticLib Header)
else(DEV_BUILD)
    set(CPACK_PACKAGE_NAME ${CMAKE_PROJECT_NAME})
    set(CPACK_COMPONENTS_ALL Exec Lib)
endif(DEV_BUILD)

set(CPACK_PACKAGE_VENDOR "WasmVM")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "A WebAssembly virtual machine implementation")
set(CPACK_VERBATIM_VARIABLES True)
set(CPACK_PACKAGE_INSTALL_DIRECTORY "/")
set(CPACK_OUTPUT_FILE_PREFIX ${PROJECT_ROOT}/packages)


set(CPACK_THREADS 0)

set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Luis Hsu")
set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA
    ${CMAKE_CURRENT_LIST_DIR}/triggers
)
set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)

include(CPack)